/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package interview.case.summer21

import interview.case.summer21.model.ITextBox
import interview.case.summer21.model.Rectangle
import interview.case.summer21.model.TextBox
import interview.case.summer21.model.WordBox
import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper


fun main(args: Array<String>) {

    val pdfData = ResourceLoader.loadPdfData("/import2.pdf")
            ?: throw IllegalArgumentException("Could not load pdf")
    val pdfDocument = PdfTextExtractor().extractDocument(pdfData)
    val words = pdfDocument.pages.first().words
    val threshold = 3f
    val mergedWords = words.fold(listOf<ITextBox>()) { acc, curr ->
        if (acc.isEmpty()) {
            acc + curr
        } else if (acc.last().box.intersects(curr.box.growLeft(threshold))) {
            val boxes = listOf(acc.last(), curr)
            val mergedBox = WordBox(
                    text = boxes.joinToString("") { it.text },
                    box = Rectangle.union(boxes.map { it.box }),
                    baseLineY = boxes.map { it.baseLineY }.average().toFloat()
            )
            acc.dropLast(1) + mergedBox
        } else {
            acc + curr
        }
    }
    val randomizedWords = mergedWords.shuffled()

    val mapper = jacksonObjectMapper().writerWithDefaultPrettyPrinter()
    val json = mapper.writeValueAsString(randomizedWords)
    println(json)
}
